### ISSUE TITLE
Lowercase alignments go straight to other_count

### ISSUE THREAD

**Issue by DarianHole** [cov-ert/type_variants#1]
First, thank you for this great program, it is easy to use and allows me to show which important snps and deletions are in our sequencing data quickly!

I've only worked on the nucleotide snps so far and I've come across an issue where my alignment files are lowercase (as I am using mafft) and the program then does not count them as detected snps in which they end up in the other_count category as seen below.

![image](https://user-images.githubusercontent.com/46600008/102914704-520e4b00-4446-11eb-89d6-019483add306.png)

I don't know if this is intended behaviour but I just added a `.upper()` to the sequence record and it worked as intended:

![image](https://user-images.githubusercontent.com/46600008/102914736-5cc8e000-4446-11eb-9d63-301738bdfe61.png)

**Comment by benjamincjackson** [comment]
Sorry that this took so long - things have been busy!

**Comment by DarianHole** [comment]
No worries! I feel that greatly, thanks for the update!
