### ISSUE TITLE
Option to identify common mutations for a subset of genomes

### ISSUE THREAD

**Issue by rambaut** [cov-ert/type_variants#5]
If the user supplies a subset list of genomes then the software could print out a list of mutations that are common to that set relative to the background (the rest of the genomes). A threshold could be given of the minimum frequency in the ingroup.

**Comment by benjamincjackson** [comment]
I'm going to write this in go and put it elsewhere. Should the input be two sets of genomes (subset + background), and the output be differences between them? This is sort of the other way around to this thing (genomes -> mutations that distinguish them  _vs_ mutations -> which genomes have them)?

**Comment by benjamincjackson** [comment]
I think that [scorpio](https://github.com/cov-lineages/scorpio) does this now.
