### ISSUE TITLE
Differentiate between missing data and untranslatable codon

### ISSUE THREAD

**Issue by jaquol** [cov-ert/type_variants#6]
From the [tool documentation](https://github.com/cov-ert/type_variants):

> For amino acids, X denotes missing data/an untranslatable codon

Can the tool output a different character for missing data (e.g. "N"?) and untranslatable codon?

Thank you in advance!

**Comment by benjamincjackson** [comment]
Hello, 

I don't want to use an N for missing data because it is also the IUPAC amino acid code for Asparagine.

Could you give me an example of two codons, one of which is untranslatable, and the other of which has missing data, so that I can think about how the two cases are different and how we should handle them?

Thanks,

Ben

**Comment by jaquol** [comment]
Hello Ben,

I see your rational for not using N. 

You mean all untranslatable codons will result from missing data in the input consensus FASTA, right?

Thank you!

Javier

**Comment by rambaut** [comment]
`CCN` is a translatable codon because it is always a `P` irrespective of what the `N` is, whereas `CAN` could either be a `Q` or an `H` and is thus untranslatable (and is denoted `X`). `NNN` is also denoted as `X`.

**Comment by benjamincjackson** [comment]
@jaquol sorry, I probably confused things initially more than I helped.

I believe that the current behaviour is: 
    `CCN` will aways be translated to `P` by `type_variants` and `CAN` or `NNN` will be `X`
    `CC-` (or any other codon which is partially or completely gaps in the input alignment) will also return `X`.
    
All I was really trying to understand with my first response was whether there was a specific case that you had in mind which you could give as an example with the following things included:

1. the input
2. the current output
3. what you would prefer the output to be

just to help me understand exactly what behaviour you are requesting (apologies if I'm being slow on the uptake).

**Comment by jaquol** [comment]
Thank you @benjamincjackson for the additional explanation, which makes sense! I guess that `X` for `CAN`, `NNN` or `CC-` is informative enough.
