### ISSUE TITLE
What is the meaning of "-" for amino acids changes

### ISSUE THREAD

**Issue by geocarvalho** [cov-ert/type_variants#7]
Hello guys, thanks to make this work available.
For the amino acid change `aa:N:D377Y` sometimes we found `D`, `Y`, `X`, and `-`.
But I don't know what exactly is `-` for this case, could you explain more about it?

In the [Differentiate between missing data and untranslatable codon](https://github.com/cov-ert/type_variants/issues/6) discussion, I saw that @benjamincjackson explains:

"`CC-` (or any other codon which is partially or completely gaps in the input alignment) will also return `X`."

So, `-` for `aa:N:D377Y` is not a partial or complete gap, right?

Thank you.

**Comment by benjamincjackson** [comment]
Hi @geocarvalho, is it possible for you to share a sequence that gives you that result?

At this point I'm not sure why you get a `-`. You are correct that it shouldn't represent a gap.

**Comment by geocarvalho** [comment]
Hello @benjamincjackson, sorry for the time. Here is an example of aligned FASTA where the table result has a `-` for `aa:N:D377Y`.

The command we are using:
```
python /path/to/type_variants.py --fasta-in /path/to/consensus_aligned/sample15.aligned.fasta --variants-config /path/to/variants_config.csv --reference /path/to/MN908947.fa --variants-out /path/to/sample15.variant_table.csv --append-genotypes
```

And we are using the the version with commit `c82cd16120d0b55139f59a4769bf287cccea740f`

[sample15.aligned.fasta.zip](https://github.com/cov-ert/type_variants/files/6987652/sample15.aligned.fasta.zip)

PS.: Please make sure to delete this file when you finish your analysis.

**Comment by geocarvalho** [comment]
Hello, @benjamincjackson. Did you download the data example I sent here?

**Comment by benjamincjackson** [comment]
Okay, I think I have gotten to the bottom of this. 

So to answer your original question, the meaning of `-` in your output of type_variants is that the codon in the alignment is `---` (a deletion covers the entire codon).

You can see this if you look at your file (codon 377 in N starts at 1-based position 29402):

```
~/programs/type_variants/issue @c82cd161* ❯ cut -c 29402-29404 sample15.aligned.fasta

---
```

I think that biopython's default behavour for treating gaps has changed in between the version that I had when I wrote type_variants and the current version. Previously the default behaviour, if you didn't specify the gap character as `-` seems to have been that the codon `---` was invalid, but now it is treated differently. I will update the script and the readme to try to deal with this consistently regardless of biopython version. Apologies for the confusion.

**Comment by geocarvalho** [comment]
@benjamincjackson Thank you for your support on this. Should I close this ticket?

Regards.

**Comment by benjamincjackson** [comment]
Thanks, I can close this now.
