### ISSUE TITLE
Plans to update constellations with delta variants

### ISSUE THREAD

**Issue by matt-sd-watson** [cov-ert/type_variants#8]
Hello, 

I was wondering if there were any plans to update the constellations for this tool with the latest VOCs and sub-lineages, in particular B.1.617.2 and its numerous AY sub-lineages. I would also be happy to write up the constellations for certain sub-lineages if there is interest in maintaining them for this tool. 

Thanks!

**Comment by benjamincjackson** [comment]
Hi,

I don't have any immediate plans to add or maintain new constellations for this tool. It's not really under active development at the moment, in favour of [Scorpio](https://github.com/cov-lineages/scorpio), and [the constellations repo in the same organisation](https://github.com/cov-lineages/constellations), which you might find useful? 

But this isn't at all meant as a hard "no" - pull requests are welcome and if it would be helpful to people then we can add them.

Thanks,

Ben

**Comment by matt-sd-watson** [comment]
Hi Ben, 

Thanks for the comment! I had suspected as such, and have been using both of the other repositories for different analyses. I will close this issue and if I find that I need to run type-variants in the future with updated constellations, maybe I will add them myself.
